name: Atualização de Dados

on:
  schedule:
    - cron: '0 */1 * * *'  # Executa a cada hora
  workflow_dispatch:  # Permite a execução manual do workflow

jobs:
  fetch_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checar código
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Instalar dependências
        run: npm install

      - name: Executar script
        run: |
          node index.js
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}  # Passa o token como variável de ambiente
