name: Atualização a cada 30 minutos

on:
  schedule:
    - cron: '*/30 * * * *' # Roda a cada 30 minutos
  workflow_dispatch: # Permite a execução manual

jobs:
  fetch_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checar código
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Instalar dependências
        run: npm install

      - name: Executar script e capturar saída
        run: node index.js > dados.json

  update_data:
    runs-on: ubuntu-latest
    needs: fetch_data  # Espera o trabalho fetch_data terminar
    steps:
      - name: Instalar jq
        run: sudo apt-get install jq

      - name: Atualizar dados.json via API do GitHub
        run: |
          FILE_CONTENT=$(cat dados.json)
          echo "${FILE_CONTENT}" | jq -Rsa . > dados_base64.txt # Codifica o conteúdo em base64
          BASE64_CONTENT=$(cat dados_base64.txt)
          curl -X PUT -H "Authorization: token ${{ secrets.GH_PAT }}" \
          -H "Accept: application/vnd.github.v3+json" \
          -d "{\"message\": \"Atualização de dados\", \"content\": \"$BASE64_CONTENT\", \"sha\": \"$(git rev-parse HEAD:main:dados.json)\"}" \
          https://api.github.com/repos/kauacodex/rj/contents/dados.json
