name: Auto Update!

on:
  schedule:
    - cron: '20,50 * * * *'  # Executa nos minutos 20 e 50 de cada hora
  workflow_dispatch:  # Permite a execução manual do workflow

jobs:
  fetch_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checar código
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Configurar fuso horário para São Paulo
        run: |
          echo "TZ=America/Sao_Paulo" >> $GITHUB_ENV  # Define o fuso horário

      - name: Instalar dependências
        run: npm install

      - name: Executar script
        run: |
          node index.js
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}  # Passa o token como variável de ambiente
